import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart';

/// The global service locator. Use [getIt<T>()] anywhere in the app to
/// resolve a registered dependency.
///
/// All registrations are generated by injectable into [injection.config.dart].
/// Run the following command after adding or changing @injectable annotations:
///
///   flutter pub run build_runner build --delete-conflicting-outputs
final GetIt getIt = GetIt.instance;

/// Called once in [main()] before [runApp()].
/// Returns a Future because [AppModule.sharedPreferences] is @preResolve.
@InjectableInit(
  initializerName: r'$initGetIt',
  preferRelativeImports: true,
  asExtension: false,
)
Future<void> configureDependencies() async => $initGetIt(getIt);
